// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWoGWv6DzKLMSGGX1zTcS_OBpMQlcauQQ',
    appId: '1:16742796419:web:5ebbcdf065410a3e3c5fb6',
    messagingSenderId: '16742796419',
    projectId: 'vegapp-fc5fb',
    authDomain: 'vegapp-fc5fb.firebaseapp.com',
    storageBucket: 'vegapp-fc5fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0LnF998MA1_y6_gdkUlfaH8sk8M2kGRQ',
    appId: '1:16742796419:android:985ec05af0f463123c5fb6',
    messagingSenderId: '16742796419',
    projectId: 'vegapp-fc5fb',
    storageBucket: 'vegapp-fc5fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIgv2x_ZQH-AX3e5zKEtncuC9tJrnx1w0',
    appId: '1:16742796419:ios:021737ecb05ee7ef3c5fb6',
    messagingSenderId: '16742796419',
    projectId: 'vegapp-fc5fb',
    storageBucket: 'vegapp-fc5fb.firebasestorage.app',
    iosBundleId: 'com.example.khodarkomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIgv2x_ZQH-AX3e5zKEtncuC9tJrnx1w0',
    appId: '1:16742796419:ios:021737ecb05ee7ef3c5fb6',
    messagingSenderId: '16742796419',
    projectId: 'vegapp-fc5fb',
    storageBucket: 'vegapp-fc5fb.firebasestorage.app',
    iosBundleId: 'com.example.khodarkomApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWoGWv6DzKLMSGGX1zTcS_OBpMQlcauQQ',
    appId: '1:16742796419:web:5ebbcdf065410a3e3c5fb6',
    messagingSenderId: '16742796419',
    projectId: 'vegapp-fc5fb',
    authDomain: 'vegapp-fc5fb.firebaseapp.com',
    storageBucket: 'vegapp-fc5fb.firebasestorage.app',
  );

}